import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex`}>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
